apiVersion: v1
kind: Service
metadata:
  name: k8-node-app-service
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: webfairooz
  namespace: flux-node-exercise
spec:
  type: LoadBalancer
  selector:
    app: node-gitops-foundations
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
