apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-node-app-deployment
spec:
  replicas: 9
  template:
    spec:
      containers:
        - name:
          image: webfairooz/gitops-foundations:1.0
