apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-node-app-deployment
  namespace: flux-node-exercise
  labels:
    app: node-gitops-foundations
spec:
  selector:
    matchLabels:
      app: node-gitops-foundations
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: node-gitops-foundations
    spec:
      containers:
        - name: kube-node-app
          image: webfairooz/k8-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
