apiVersion: v1
kind: Service
metadata:
  name: k8-node-app-prod-service
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: webfairooz
  namespace: flux-node-exercise-prod
spec:
  type: LoadBalancer
  selector:
    app: node-prod-gitops-foundations
  ports:
    - port: 80
      targetPort: 8080
